Y2/UI/Controllers/public_charController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using BLL;
using IBLL;
using IocContianer;
namespace UI.Controllers
{
    public class public_charController : Controller
    {
        Ipublic_charBLL ioc = iocCreate.CreateTextBll<Ipublic_charBLL>("public_charBLL");
        // GET: public_char
        public ActionResult Index()
        {
            List<config_public_char> list = ioc.Select();
            return View(list);
        }

        // GET: public_char/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: public_char/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: public_char/Create
        [HttpPost]
        [ActionName("add")]
        public ActionResult Create(config_public_char t)
        {
            if (ModelState.IsValid)
            {
      
                int num = ioc.Insert(t);
                if (num > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        // GET: public_char/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: public_char/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: public_char/Delete/5
        public ActionResult Delete(short id)
        {
            config_public_char stu = new config_public_char()
            {
                pbc_id = id
            };
            int num = ioc.Del(stu);
            if (num > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(num);
            }
        }

        // POST: public_char/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Y2/UI/Views/public_char/Create.cshtml
@model Entity.config_public_char

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet"
          href="../../css/table.css" type="text/css">
    <script type="text/javascript"
            src="../../javascript/comm/comm.js">
    </script>
</head>

<script type="text/javascript">
		function check(){
			if (document.getElementById("publicChar.attributeKind").value==""){
				alert("属性种类不能为空!!!");
				return false;
			}
			if (document.getElementById("publicChar.attributeName").value==""){
				alert("属性名称不能为空!!!");
				return false;
			}
			document.forms[0].submit();
		}
</script>

<body>
@using (Html.BeginForm("add", "public_char"))
{
    @Html.ValidationSummary(true)
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--公共属性设置--公共属性添加
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="submit" value="提交" class="BUTTON_STYLE1">
                    <input type="button" value="返回" class="BUTTON_STYLE1"
                           onclick="history.back();">
                </td>
            </tr>
        </table>

        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td class="TD_STYLE1" width="19%">
                    属性种类
                </td>
                <td class="TD_STYLE2" width="81%">
                    @Html.EditorFor(model => model.attribute_kind, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model=>model.attribute_kind)
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    属性名称
                </td>
                <td class="TD_STYLE2">
                    @Html.EditorFor(model => model.attribute_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.attribute_name)
                </td>
            </tr>
        </table>
}
</body>
</html>

Y2/UI/Views/public_char/Index.cshtml
@model IEnumerable<Entity.config_public_char>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet"
          href="../../css/table.css" type="text/css">
    <script type="text/javascript"
            src="../../javascript/comm/comm.js">
    </script>

    <script type="text/javascript" src="../../javascript/jquery-1.7.2.js"></script>

    <script type="text/javascript">
			function deletePublicChar(id){
				$.ajax({
						url:"http://127.0.0.1:8080/HR_Fist/customiz/customizAction!doDeletePublicChar",
						data:"cpc.pbcId="+id,
						dataType:"text",
						success:function (){
							alert("删除成功！");
							location.reload();
						},
						type:"post"
					});
			}
    </script>
</head>
<body>
    <form method="post" action="../customiz/customizAction!findPublicChar">
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--公共属性设置
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="button" value="添加" class="BUTTON_STYLE1"
                           onclick="window.location.href = 'public_char/Create';">
                </td>
            </tr>
        </table>
        <table width="100%" border="0" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td width="49%" class="TD_STYLE1">
                    属性种类
                </td>
                <td width="44%" class="TD_STYLE1">
                    属性名称
                </td>
                <td width="7%" class="TD_STYLE1" align="center">
                    删除
                </td>
            </tr>

            @foreach (Entity.config_public_char dr in Model)
            {
                <tr>
                    <td>@dr.attribute_kind</td>
                    <td>@dr.attribute_name </td>
                  
                    <td style="text-align:center;vertical-align:middle;">@Html.ActionLink("删除", "Delete", new { id = dr.pbc_id }, new { onclick = "return confirm('亲，你确定要删除吗？')" })</td>
                </tr>
            }

        </table>
 
</body>
</html>