Y2/UI/Controllers/second_kindController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using BLL;
using IBLL;
using IocContianer;
namespace UI.Controllers
{
    public class second_kindController : Controller
    {
        // GET: second_kind
        Isecond_kindBLL ioc = iocCreate.CreateTextBll<Isecond_kindBLL>("second_kindBLL");
        Ifirst_kindBLL fbll = iocCreate.CreateTextBll<Ifirst_kindBLL>("first_kindBLL");
        public ActionResult Index()
        {
            List<config_file_second_kind> list = ioc.Select();
            return View(list);
        }

        // GET: second_kind/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        private void GetList()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var xllist = fbll.SelectAll(); /*st.BanJiClass.Select(e => e);*/
            foreach (var item in xllist)
            {
                SelectListItem c = new SelectListItem()
                {
                    Text = item.first_kind_name,
                    Value = item.first_kind_id
                };
             
                list.Add(c);   
              
            }
            ViewData["dt"] = list;
        }

        // GET: second_kind/Create
        public ActionResult Create()
        {
            GetList();
            return View();
        }

        // POST: second_kind/Create
        [HttpPost]
        [ActionName("add")]
        public ActionResult Create(config_file_second_kind se)
        {
            if (ModelState.IsValid)
            {
                List<config_file_second_kind> xx = ioc.Select();
                config_file_second_kind cfk = xx[xx.Count - 1];
                config_file_first_kind fk = fbll.selectWhere(e => e.first_kind_id == se.first_kind_id).FirstOrDefault();

                se.second_kind_id = (Convert.ToInt32(cfk.second_kind_id) + 1001).ToString().Substring(2);
                se.first_kind_name = fk.first_kind_name;
                int num = ioc.Insert(se);
                if (num > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        // GET: second_kind/Edit/5
        public ActionResult Edit(short id)
        {
            config_file_second_kind li = ioc.selectWhere(e => e.fsk_id == id).FirstOrDefault();

            return View(li);
        }

        // POST: second_kind/Edit/5
        [HttpPost]
        public ActionResult Edit(config_file_second_kind t)
        {
            int num = ioc.Update(t);
            if (num > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(num);
            }
        }

        // GET: second_kind/Delete/5
        public ActionResult Delete(short id)
        {
            config_file_second_kind stu = new config_file_second_kind()
            {
                fsk_id = id
            };
            int num = ioc.Del(stu);
            if (num > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(num);
            }
        }

        // POST: second_kind/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Y2/UI/Views/second_kind/Create.cshtml
@model Entity.config_file_second_kind

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet"
          href="../../css/table.css" type="text/css">
    <script type="text/javascript"
            src="../../javascript/comm/comm.js">
    </script>
</head>

<script type="text/javascript">
		function check(){
			if (document.getElementById("firstKind.ffkId").value==0){
				alert("请选择I级机构名称!!!");
				return false;
			}
			if (document.getElementById("secondKind.secondKindName").value==""){
				alert("II级机构名称不能为空!!!");
				return false;
			}
			if (document.getElementById("secondKind.secondSalaryId").value==""){
				alert("薪酬发放责任人编号不能为空!!!");
				return false;
			}
			if (document.getElementById("secondKind.secondSaleId").value==""){
				alert("销售责任人编号不能为空!!!");
				return false;
			}
			document.forms[0].submit();
		}
		function change(){
		var se=document.getElementById("firstKindId");
		document.getElementById("firstKindName").value=se.options[se.selectedIndex].innerHTML;

		}
</script>
<body>
    @using (Html.BeginForm("add", "second_kind"))
    {
        @Html.ValidationSummary(true)
        <input type="hidden" id="firstKindName" name="cfsk.firstKindName">
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--II级机构设置--II级机构添加
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="submit" value="提交" class="BUTTON_STYLE1">
                    <input type="button" value="返回" class="BUTTON_STYLE1"
                           onclick="history.back();">
                </td>
            </tr>
        </table>


        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td width="19%" class="TD_STYLE1">
                    I级机构名称
                </td>
                <td width="81%" class="TD_STYLE2">
                    @Html.DropDownListFor(e => e.first_kind_id, ViewData["dt"] as IEnumerable<SelectListItem>)
                    @Html.ValidationMessageFor(model => model.first_kind_id)
                </td>
            </tr>
            <tr>
                <td width="19%" class="TD_STYLE1">
                    II级机构编号
                </td>
                <td width="81%" class="TD_STYLE2"></td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    II级机构名称
                </td>
                <td class="TD_STYLE2">
                    @Html.EditorFor(model => model.second_kind_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model=>model.second_kind_name)
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    薪酬发放责任人编号（多个编号之间请用"半角逗号"加"一个空格"隔开，如", "）
                </td>
                <td class="TD_STYLE2">
                    @*@Html.EditorFor(model => model.second_salary_id, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.TextAreaFor(model => model.second_salary_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.second_salary_id)
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    销售责任人编号（多个编号之间请用"半角逗号"加"一个空格"隔开，如", "）
                </td>
                <td class="TD_STYLE2">
                    @Html.TextAreaFor(model => model.second_sale_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.second_sale_id)
                </td>
            </tr>
        </table>
    }
    }
</body>
</html>

Y2/UI/Views/second_kind/Edit.cshtml
@model Entity.config_file_second_kind

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/javascript/jquery-1.7.2.js"></script>
    <link rel="stylesheet" href="../../css/table.css"
          type="text/css"></link>
    <script type="text/javascript"
            src="../../javascript/comm/comm.js">
    </script>

    <script type="text/javascript">
	//控件判断不能为空
	function check(){
		if (document.getElementById("secondKind.secondSalaryId").value==""){
			alert("薪酬发放责任人编号不能为空!!!");
			return false;
		}
		if(document.getElementById("secondKind.secondSaleId").value==""){
			alert("销售责任人编号不能为空!!!");
			return false;
		}
		document.forms[0].submit();
	}

	$(function () {

	 

	 
	   
	})
    </script>
</head>


<body>

   @using (Html.BeginForm("Edit", "second_kind", FormMethod.Post))
   {
    @Html.ValidationSummary(true)
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--II级机构设置--II级机构变更
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="submit" value="提交" class="BUTTON_STYLE1">
                    <input type="button" value="返回" class="BUTTON_STYLE1"
                           onclick="history.back();">
                </td>
            </tr>
        </table>

        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <input type="hidden" name="cfsk.fskId" value=761 class="INPUT_STYLE1" />
            <tr>
                <td width="19%" class="TD_STYLE1">
                    I级机构名称
                </td>
                <td style="display:none">
                    @Html.EditorFor(model => model.fsk_id, new { htmlAttributes = new { @class = "form-control" } })

                </td>
                <td width="81%" class="TD_STYLE2"  >
                    @Html.EditorFor(model => model.first_kind_name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </td>
            </tr>
            <tr>
                <td width="19%" class="TD_STYLE1">
                    II级机构编号
                </td>
                <td width="81%" class="TD_STYLE2">
                    @Html.EditorFor(model => model.second_kind_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    II级机构名称
                </td>
                <td class="TD_STYLE2">
                    @Html.EditorFor(model => model.second_kind_name, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly" }})
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    薪酬发放责任人编号（多个编号之间请用"半角逗号"加"一个空格"隔开，如", "）
                </td>
                <td class="TD_STYLE2">
                    @Html.TextAreaFor(model => model.second_salary_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model=>model.second_salary_id)
                </td>
            </tr>
            <tr>
                <td class="TD_STYLE1">
                    销售责任人编号（多个编号之间请用"半角逗号"加"一个空格"隔开，如", "）
                </td>
                <td class="TD_STYLE2">
                    @Html.TextAreaFor(model => model.second_sale_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.second_sale_id)
                </td>
            </tr>
        </table>
   }
    
    }
</body>
</html>

Y2/UI/Views/second_kind/Index.cshtml
@model List<Entity.config_file_second_kind>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="~/javascript/jquery-1.7.2.js"></script>

    <script src="~/javascript/vue.js"></script>
    <link rel="stylesheet" href="../../css/table.css"
          type="text/css"></link>
    <script type="text/javascript"
            src="../../javascript/comm/comm.js">
    </script>
</head>

<script type="text/javascript">

		function submission(){
			document.forms[0].submit();
		}

		function page(currentPage){
			document.getElementById("pid").value=currentPage;
			document.forms[0].submit();
		}
</script>


<body>
    <form action="../customiz/customizAction!findSecondKind" method="post">
        <table width="100%">
            <tr>
                <td>
                    <font color="black">
                        您正在做的业务是：人力资源--客户化设置--人力资源档案管理设置--II级机构设置
                    </font>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <input type="button" value="添加" class="BUTTON_STYLE1"
                           onclick="window.location.href = 'second_kind/Create'" />
                </td>
            </tr>
        </table>
        <table width="100%" border="1" cellpadding=0 cellspacing=1
               bordercolorlight=#848284 bordercolordark=#eeeeee
               class="TABLE_STYLE1">
            <tr>
                <td width="15%" class="TD_STYLE1">
                    I级机构名称
                </td>
                <td width="15%" class="TD_STYLE1">
                    II级机构编号
                </td>
                <td width="15%" class="TD_STYLE1">
                    II级机构名称
                </td>
                <td width="22%" class="TD_STYLE1">
                    薪酬发放责任人编号
                </td>
                <td width="22%" class="TD_STYLE1">
                    销售责任人编号
                </td>
                <td width="5%" class="TD_STYLE1">
                    变更
                </td>
                <td width="5%" class="TD_STYLE1">
                    删除
                </td>
            </tr>
            @foreach (Entity.config_file_second_kind dr in Model)
            {
                <tr>
                    <td>@dr.first_kind_name</td>
                    <td>@dr.second_kind_id </td>
                    <td>@dr.second_kind_name</td>
                    <td>@dr.second_salary_id </td>
                    <td>@dr.second_sale_id</td>

                    <td> @Html.ActionLink("变更", "Edit", new { id = @dr.fsk_id })</td>
                    <td>@Html.ActionLink("删除", "Delete", new { id = dr.fsk_id }, new { onclick = "return confirm('亲，你确定要删除吗？')" })</td>
                </tr>
            }
           

        </table>
        <br><br>
        <th colspan="7" class="pager"></th>
        <p>
    </form>
</body>
</html>